### ISSUE TITLE
Junit report?

### ISSUE THREAD

**Issue by billieblaze** [Zarkonnen/se-interpreter#36]
Running this local and experimenting w/ sauce + sauce onDemand jenkins plugin.    Not REALLY seeing a way to grab a junit report from this.  Am i missing something?

**Comment by DylanLacey** [comment]
Would it be possible to merge the junit-listener into the base project's utils, given the usefulness for CI?

**Comment by gregmoser** [comment]
It would be really great if this got added to the se-interpreter.  We use CircleCI instead of travis because it allows you to actually read and parse jUnit xml as part of the notification.  If someone were to issue a formal PR, would it be accepted into the core?

**Comment by Zarkonnen** [comment]
Sure! Does it have to be built into interpreter.js or could it just live in utils/?

**Comment by gregmoser** [comment]
I'm not exactly sure where it should go, because I don't know how a lot of this works.  I guess I'm just hoping that I can take something like this: https://github.com/davidlinse/se-interpreter/blob/integration/listener/junit-listener.js from @davidlinse could be added to the core and documented so that I can figure out how to have these xml style reports be saved to a local file so that circleCI can pick it up :)

**Comment by gregmoser** [comment]
NVMD, I just figured out how to use listeners (I read the README docs again, duh!) which I think will allow me to do the JUnit reporting that I want.  I guess it would just be nice if the 'out-of-the-box' version of this automatically had that JUnit listener that @davidlinse created as part of the utils folder.
