### ISSUE TITLE
--browser-browserName=chrome

### ISSUE THREAD

**Issue by emailvacharya** [Zarkonnen/se-interpreter#45]
Hi, 
I am trying to execute example.json file on chrome from cmd. Below is my command
>Java -jar SeInterpreter.jar --browser-browserName=chrome full_example.json. 
I am getting an exception. See below stack trace
Mar 30, 2015 11:19:53 AM com.sebuilder.interpreter.SeInterpreter main
SEVERE: Run error.
java.io.FileNotFoundException: --browser-browserName=chrome (The system cannot f
ind the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.sebuilder.interpreter.factory.ScriptFactory.parse(ScriptFactory.j
ava:206)
        at com.sebuilder.interpreter.SeInterpreter.main(SeInterpreter.java:99)

Thanks
Vijay

**Comment by Zarkonnen** [comment]
Hey Vijay,

The issue is that you're invoking the Java version with a flag that 
looks like it's from the node.js version. So the reason it's going "file 
not found" is that it's literally trying to load a script of the name 
"--browser-browserName=chrome"!

The flag you would want to use is

--driver=Chrome

but you'll also have to implement 
com.sebuilder.interpreter.webdriverfactory.Chrome, something that 
*really* should already be in there but evidently isn't yet. (There's 
only Firefox and Remote factories.)

- David

**Comment by emailvacharya** [comment]
Thanks Dave. I have Java 8 installed. Shall I downgrade to 6 or 7 ?

Thanks
Vijay

**Comment by emailvacharya** [comment]
This issue is now resolved. I used node interpreter instead of Java. 
Thanks
